# docker build -f Dockerfile.build -t biplifes/llm-llama:latest --platform=linux/amd64 .
# docker push biplifes/llm-llama:latest 
FROM nvidia/cuda:12.6.1-runtime-ubuntu24.04

WORKDIR /app
COPY src /app

RUN \
  apt-get update && \
  apt-get install -y nodejs npm && \
  npm install && \
  apt-get remove --purge -y npm && \
  apt-get autoremove -y && \
  rm -rf /var/lib/apt/lists/*
