# docker build -f Dockerfile.build -t biplifes/llm-llama:latest --platform=linux/amd64 .
# docker push biplifes/llm-llama:latest 
FROM nvidia/cuda:12.6.1-base-ubuntu24.04

RUN apt update -y && apt install -y nodejs npm

WORKDIR /app
COPY src .
COPY ./meta-llama-3.1-8b-instruct-q4_k_m.gguf /model/meta-llama-3.1-8b-instruct-q4_k_m.gguf

RUN npm install